/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agecalculator;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.util.Date;
import java.util.Calendar;
import java.time.Period;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahmudul Hasan
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setDateOfToday();
        homePanel.setVisible(true);
        functionPanel.setVisible(false);
    }
    int birthDate_int,birthMonth_int,birthYear_int;
    LocalDate today= LocalDate.now();
    Date Today=new Date();
    /**
     * for getting current date
     * @return string date
     */
    void setDateOfToday(){
    SimpleDateFormat sd=new SimpleDateFormat("dd");
    String date=sd.format(Today);
    SimpleDateFormat sd1=new SimpleDateFormat("MM");
    String month=sd1.format(Today);
    SimpleDateFormat sd2=new SimpleDateFormat("yyyy");
    String year=sd2.format(Today);
    todayDate.setText(date);
    todaysMonth.setText(month);
    todaysYear.setText(year);
    }
    int calculateYears(int year, int month, int date){
     LocalDate BirthDay= LocalDate.of(year, month, date);
        int years=Period.between(BirthDay ,today).getYears();
        return years;
    }
    int calculateDays(int year, int month, int date){
     LocalDate BirthDay= LocalDate.of(year, month, date);
        int days=Period.between(BirthDay,today).getDays();
        return days;
    }
    int calculateMonths(int year, int month, int date){
     LocalDate BirthDay= LocalDate.of(year, month, date);
        int months=Period.between(BirthDay,today ).getMonths();
        return months;
    }
    void showCalculated(){
        
            try {
                getBirthday();
                int years=calculateYears(birthYear_int, birthMonth_int, birthDate_int);
                int months=calculateMonths(birthYear_int, birthMonth_int, birthDate_int);
                int days=calculateDays(birthYear_int, birthMonth_int, birthDate_int);
                homePanel.setVisible(false);
                functionPanel.setVisible(true);
                lbOutpt.setText(""+years+"Years "+months+"Months "+days+"Days old");
            } catch (Exception e) {
              }
        
    }
    void getBirthday(){   
    birthDate_int=Integer.parseInt(txtDate.getText());
    birthMonth_int=Integer.parseInt(""+comMonth.getSelectedIndex());
    birthYear_int=Integer.parseInt(txtYear.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        homePanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comMonth = new javax.swing.JComboBox<>();
        txtYear = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        todayDate = new javax.swing.JTextField();
        todaysMonth = new javax.swing.JTextField();
        todaysYear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SubmitPanel = new javax.swing.JPanel();
        submit = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        functionPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbOutpt = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Simply calculate you age!");
        homePanel.add(jLabel17);
        jLabel17.setBounds(0, 0, 500, 80);

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Enter your BirthDay");
        homePanel.add(jLabel12);
        jLabel12.setBounds(90, 80, 330, 50);

        comMonth.setBackground(new java.awt.Color(255, 255, 255));
        comMonth.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        comMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        homePanel.add(comMonth);
        comMonth.setBounds(160, 130, 150, 60);

        txtYear.setBackground(new java.awt.Color(255, 255, 255));
        txtYear.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        homePanel.add(txtYear);
        txtYear.setBounds(310, 130, 100, 60);

        txtDate.setBackground(new java.awt.Color(255, 255, 255));
        txtDate.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        homePanel.add(txtDate);
        txtDate.setBounds(90, 130, 64, 60);

        todayDate.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        todayDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        homePanel.add(todayDate);
        todayDate.setBounds(90, 250, 100, 60);

        todaysMonth.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        todaysMonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        todaysMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todaysMonthActionPerformed(evt);
            }
        });
        homePanel.add(todaysMonth);
        todaysMonth.setBounds(190, 250, 90, 60);

        todaysYear.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        todaysYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        homePanel.add(todaysYear);
        todaysYear.setBounds(280, 250, 130, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\Rectangle 3.png")); // NOI18N
        homePanel.add(jLabel2);
        jLabel2.setBounds(0, -10, 500, 90);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\Rectangle 4.png")); // NOI18N
        homePanel.add(jLabel5);
        jLabel5.setBounds(60, 110, 380, 100);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\Todays Date.png")); // NOI18N
        homePanel.add(jLabel7);
        jLabel7.setBounds(130, 200, 220, 40);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\Rectangle 4.png")); // NOI18N
        homePanel.add(jLabel6);
        jLabel6.setBounds(60, 230, 380, 100);

        ExitPanel.setBackground(new java.awt.Color(192, 57, 43));
        ExitPanel.setLayout(null);

        Exit.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(0, 0, 0));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        ExitPanel.add(Exit);
        Exit.setBounds(20, 16, 180, 50);

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\Rectangle 6.png")); // NOI18N
        ExitPanel.add(jLabel8);
        jLabel8.setBounds(10, 10, 200, 58);

        homePanel.add(ExitPanel);
        ExitPanel.setBounds(140, 420, 220, 80);

        SubmitPanel.setBackground(new java.awt.Color(192, 57, 43));
        SubmitPanel.setLayout(null);

        submit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submit.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\Submit.png")); // NOI18N
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
        });
        SubmitPanel.add(submit);
        submit.setBounds(20, 20, 180, 40);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\Rectangle 6.png")); // NOI18N
        SubmitPanel.add(jLabel13);
        jLabel13.setBounds(10, 10, 200, 58);

        homePanel.add(SubmitPanel);
        SubmitPanel.setBounds(140, 330, 220, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\Rectangle 2.png")); // NOI18N
        homePanel.add(jLabel1);
        jLabel1.setBounds(0, -10, 530, 540);

        jLayeredPane1.add(homePanel, "card2");

        functionPanel.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Mahmudul Hasan Shafin");
        functionPanel.add(jLabel16);
        jLabel16.setBounds(310, 490, 190, 30);

        jLabel15.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\icons8_copyright_35px_1.png")); // NOI18N
        functionPanel.add(jLabel15);
        jLabel15.setBounds(280, 490, 35, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\icons8_back_arrow_64px_1.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        functionPanel.add(jLabel4);
        jLabel4.setBounds(-3, 0, 80, 80);

        lbOutpt.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        lbOutpt.setForeground(new java.awt.Color(255, 255, 255));
        lbOutpt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        functionPanel.add(lbOutpt);
        lbOutpt.setBounds(0, 160, 500, 190);

        jLabel14.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("You are...");
        functionPanel.add(jLabel14);
        jLabel14.setBounds(0, 80, 200, 80);

        jLabel11.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Your age is here!");
        functionPanel.add(jLabel11);
        jLabel11.setBounds(0, -4, 500, 80);

        jLabel10.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\Rectangle 3.png")); // NOI18N
        functionPanel.add(jLabel10);
        jLabel10.setBounds(0, -10, 500, 90);

        jLabel9.setIcon(new javax.swing.ImageIcon("F:\\Java 23\\JavaCodes\\AgeCalculator\\src\\img\\Rectangle 2.png")); // NOI18N
        functionPanel.add(jLabel9);
        jLabel9.setBounds(0, -10, 510, 540);

        jLayeredPane1.add(functionPanel, "card3");

        jPanel1.add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 500, 520);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 520);

        setSize(new java.awt.Dimension(500, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        // TODO add your handling code here:
        SubmitPanel.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_submitMouseEntered

    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited
        // TODO add your handling code here:
       SubmitPanel.setBackground(new Color(192, 57, 43)); 
    }//GEN-LAST:event_submitMouseExited

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        ExitPanel.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        ExitPanel.setBackground(new Color(192, 57, 43)); 
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        if(!txtDate.getText().isEmpty() && comMonth.getSelectedIndex()>0){
          showCalculated();  
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter all Data!");
        }
        
    }//GEN-LAST:event_submitMouseClicked

    private void todaysMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todaysMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todaysMonthActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
        if(!txtDate.getText().isEmpty() && comMonth.getSelectedIndex()>0){
          showCalculated();  
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter all Data!");
        }
    }//GEN-LAST:event_txtYearActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(true);
        functionPanel.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JPanel SubmitPanel;
    private javax.swing.JComboBox<String> comMonth;
    private javax.swing.JPanel functionPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbOutpt;
    private javax.swing.JLabel submit;
    private javax.swing.JTextField todayDate;
    private javax.swing.JTextField todaysMonth;
    private javax.swing.JTextField todaysYear;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
